server:
  port: 3020
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/footbal_manager
    username: postgres
    password: postgres
